#!/bin/bash
# Ancient Language Library Download Script
# Generated by Ancient Language Library Builder
# Date: 2025-11-24 11:13:06

set -e  # Exit on error

BASE_DIR="/Users/coo-koba42/dev/ancient_language_library"
IMAGES_DIR="$BASE_DIR/images"
METADATA_DIR="$BASE_DIR/metadata"

# Create directories
mkdir -p "$IMAGES_DIR"
mkdir -p "$METADATA_DIR"

echo "🔍 Ancient Language Library Download Script"
echo "============================================"
echo ""

# 1. Cuneiform Digital Library Initiative (CDLI)
echo "📥 Downloading: Cuneiform Digital Library Initiative (CDLI)"
mkdir -p "$IMAGES_DIR/Cuneiform_Digital_Library_Initiative_(CDLI)"
# Source: https://cdli.mpiwg-berlin.mpg.de/
# Status: deciphered
# Multi-spectral: True
# Manual download required from: https://cdli.mpiwg-berlin.mpg.de/
# Save to: $IMAGES_DIR/Cuneiform_Digital_Library_Initiative_(CDLI)/
echo "  → Cuneiform_Digital_Library_Initiative_(CDLI)/"

# 2. Thesaurus Linguae Aegyptiae (TLA)
echo "📥 Downloading: Thesaurus Linguae Aegyptiae (TLA)"
mkdir -p "$IMAGES_DIR/Thesaurus_Linguae_Aegyptiae_(TLA)"
# Source: https://aaew.bbaw.de/tla/
# Status: deciphered
# Multi-spectral: True
# Manual download required from: https://aaew.bbaw.de/tla/
# Save to: $IMAGES_DIR/Thesaurus_Linguae_Aegyptiae_(TLA)/
echo "  → Thesaurus_Linguae_Aegyptiae_(TLA)/"

# 3. Dendera Temple Digital Archive
echo "📥 Downloading: Dendera Temple Digital Archive"
mkdir -p "$IMAGES_DIR/Dendera_Temple_Digital_Archive"
# Source: https://www.ifao.egnet.net/
# Status: partial
# Multi-spectral: True
# Manual download required from: https://www.ifao.egnet.net/
# Save to: $IMAGES_DIR/Dendera_Temple_Digital_Archive/
echo "  → Dendera_Temple_Digital_Archive/"

# 4. Schoyen Collection Linear A
echo "📥 Downloading: Schoyen Collection Linear A"
mkdir -p "$IMAGES_DIR/Schoyen_Collection_Linear_A"
# Source: https://www.schoyencollection.com/
# Status: undeciphered
# Multi-spectral: True
# Manual download required from: https://www.schoyencollection.com/
# Save to: $IMAGES_DIR/Schoyen_Collection_Linear_A/
echo "  → Schoyen_Collection_Linear_A/"

# 5. DAMOS Linear A Database
echo "📥 Downloading: DAMOS Linear A Database"
mkdir -p "$IMAGES_DIR/DAMOS_Linear_A_Database"
# Source: https://www.aegeus.eu/damos/
# Status: undeciphered
# Multi-spectral: False
# Manual download required from: https://www.aegeus.eu/damos/
# Save to: $IMAGES_DIR/DAMOS_Linear_A_Database/
echo "  → DAMOS_Linear_A_Database/"

# 6. Indus Script Digital Corpus
echo "📥 Downloading: Indus Script Digital Corpus"
mkdir -p "$IMAGES_DIR/Indus_Script_Digital_Corpus"
# Source: https://www.harappa.com/
# Status: undeciphered
# Multi-spectral: True
# Manual download required from: https://www.harappa.com/
# Save to: $IMAGES_DIR/Indus_Script_Digital_Corpus/
echo "  → Indus_Script_Digital_Corpus/"

# 7. Rongorongo Digital Archive
echo "📥 Downloading: Rongorongo Digital Archive"
mkdir -p "$IMAGES_DIR/Rongorongo_Digital_Archive"
# Source: https://www.rongorongoarchive.org/
# Status: undeciphered
# Multi-spectral: True
# Manual download required from: https://www.rongorongoarchive.org/
# Save to: $IMAGES_DIR/Rongorongo_Digital_Archive/
echo "  → Rongorongo_Digital_Archive/"

# 8. Maya Hieroglyph Database
echo "📥 Downloading: Maya Hieroglyph Database"
mkdir -p "$IMAGES_DIR/Maya_Hieroglyph_Database"
# Source: https://www.mayacodices.org/
# Status: deciphered
# Multi-spectral: True
# Manual download required from: https://www.mayacodices.org/
# Save to: $IMAGES_DIR/Maya_Hieroglyph_Database/
echo "  → Maya_Hieroglyph_Database/"

# 9. Proto-Sinaitic Inscriptions
echo "📥 Downloading: Proto-Sinaitic Inscriptions"
mkdir -p "$IMAGES_DIR/Proto-Sinaitic_Inscriptions"
# Source: https://www.orientlab.net/
# Status: partial
# Multi-spectral: True
# Manual download required from: https://www.orientlab.net/
# Save to: $IMAGES_DIR/Proto-Sinaitic_Inscriptions/
echo "  → Proto-Sinaitic_Inscriptions/"

# 10. Etruscan Texts Project
echo "📥 Downloading: Etruscan Texts Project"
mkdir -p "$IMAGES_DIR/Etruscan_Texts_Project"
# Source: https://www.etruscan.space/
# Status: partial
# Multi-spectral: False
# Manual download required from: https://www.etruscan.space/
# Save to: $IMAGES_DIR/Etruscan_Texts_Project/
echo "  → Etruscan_Texts_Project/"

# 11. Ogham in 3D
echo "📥 Downloading: Ogham in 3D"
mkdir -p "$IMAGES_DIR/Ogham_in_3D"
# Source: https://ogham.celt.dias.ie/
# Status: deciphered
# Multi-spectral: True
# Manual download required from: https://ogham.celt.dias.ie/
# Save to: $IMAGES_DIR/Ogham_in_3D/
echo "  → Ogham_in_3D/"

# 12. Oracle Bone Inscriptions
echo "📥 Downloading: Oracle Bone Inscriptions"
mkdir -p "$IMAGES_DIR/Oracle_Bone_Inscriptions"
# Source: http://www.bsm.org.cn/
# Status: deciphered
# Multi-spectral: True
# Manual download required from: http://www.bsm.org.cn/
# Save to: $IMAGES_DIR/Oracle_Bone_Inscriptions/
echo "  → Oracle_Bone_Inscriptions/"

# 13. Digital Archive for the Study of Pre-Islamic Arabian Inscriptions
echo "📥 Downloading: Digital Archive for the Study of Pre-Islamic Arabian Inscriptions"
mkdir -p "$IMAGES_DIR/Digital_Archive_for_the_Study_of_Pre-Islamic_Arabian_Inscriptions"
# Source: http://dasi.cnr.it/
# Status: deciphered
# Multi-spectral: False
# Manual download required from: http://dasi.cnr.it/
# Save to: $IMAGES_DIR/Digital_Archive_for_the_Study_of_Pre-Islamic_Arabian_Inscriptions/
echo "  → Digital_Archive_for_the_Study_of_Pre-Islamic_Arabian_Inscriptions/"

# 14. Ugarit Digital Library
echo "📥 Downloading: Ugarit Digital Library"
mkdir -p "$IMAGES_DIR/Ugarit_Digital_Library"
# Source: https://www.orient.ox.ac.uk/
# Status: deciphered
# Multi-spectral: False
# Manual download required from: https://www.orient.ox.ac.uk/
# Save to: $IMAGES_DIR/Ugarit_Digital_Library/
echo "  → Ugarit_Digital_Library/"

# 15. Wulfila Project (Gothic Bible)
echo "📥 Downloading: Wulfila Project (Gothic Bible)"
mkdir -p "$IMAGES_DIR/Wulfila_Project_(Gothic_Bible)"
# Source: https://www.wulfila.be/
# Status: deciphered
# Multi-spectral: True
# Manual download required from: https://www.wulfila.be/
# Save to: $IMAGES_DIR/Wulfila_Project_(Gothic_Bible)/
echo "  → Wulfila_Project_(Gothic_Bible)/"

# 16. Achaemenid Royal Inscriptions
echo "📥 Downloading: Achaemenid Royal Inscriptions"
mkdir -p "$IMAGES_DIR/Achaemenid_Royal_Inscriptions"
# Source: https://www.livius.org/
# Status: deciphered
# Multi-spectral: False
# Manual download required from: https://www.livius.org/
# Save to: $IMAGES_DIR/Achaemenid_Royal_Inscriptions/
echo "  → Achaemenid_Royal_Inscriptions/"

# 17. Cypro-Minoan Corpus
echo "📥 Downloading: Cypro-Minoan Corpus"
mkdir -p "$IMAGES_DIR/Cypro-Minoan_Corpus"
# Source: https://www.archaeology.ucy.ac.cy/
# Status: undeciphered
# Multi-spectral: True
# Manual download required from: https://www.archaeology.ucy.ac.cy/
# Save to: $IMAGES_DIR/Cypro-Minoan_Corpus/
echo "  → Cypro-Minoan_Corpus/"

# 18. Phaistos Disc Digital Archive
echo "📥 Downloading: Phaistos Disc Digital Archive"
mkdir -p "$IMAGES_DIR/Phaistos_Disc_Digital_Archive"
# Source: https://www.heraklionmuseum.gr/
# Status: undeciphered
# Multi-spectral: True
# Manual download required from: https://www.heraklionmuseum.gr/
# Save to: $IMAGES_DIR/Phaistos_Disc_Digital_Archive/
echo "  → Phaistos_Disc_Digital_Archive/"

# 19. Vinča Culture Signs
echo "📥 Downloading: Vinča Culture Signs"
mkdir -p "$IMAGES_DIR/Vinča_Culture_Signs"
# Source: https://www.balcanica.rs/
# Status: undeciphered
# Multi-spectral: False
# Manual download required from: https://www.balcanica.rs/
# Save to: $IMAGES_DIR/Vinča_Culture_Signs/
echo "  → Vinča_Culture_Signs/"

echo ""
echo "✅ Directory structure created!"
echo "📋 Next steps:"
echo "  1. Visit each source URL listed above"
echo "  2. Download images to corresponding directories"
echo "  3. Run: python ancient_language_library_builder.py process"
